version: '3'
services:
  db-prueba:
    image: postgres
    ports:
      - "5455:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - data-db:/var/lib/postgresql/data

volumes:
  data-db: