--
-- PostgreSQL database dump
--

-- Dumped from database version 16.1 (Debian 16.1-1.pgdg120+1)
-- Dumped by pg_dump version 16.1 (Debian 16.1-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Addresses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Addresses" (
    "Id" integer NOT NULL,
    "City" text,
    "Province" text,
    "Neighborhood" text,
    "Street" text,
    "Number" integer NOT NULL,
    "ClientUserId" integer NOT NULL
);


ALTER TABLE public."Addresses" OWNER TO postgres;

--
-- Name: Addresses_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Addresses" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Addresses_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetRoleClaims" OWNER TO postgres;

--
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


ALTER TABLE public."AspNetRoles" OWNER TO postgres;

--
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetUserClaims" OWNER TO postgres;

--
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL
);


ALTER TABLE public."AspNetUserLogins" OWNER TO postgres;

--
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL
);


ALTER TABLE public."AspNetUserRoles" OWNER TO postgres;

--
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text
);


ALTER TABLE public."AspNetUserTokens" OWNER TO postgres;

--
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUsers" (
    "Id" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


ALTER TABLE public."AspNetUsers" OWNER TO postgres;

--
-- Name: CategorieProduct; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."CategorieProduct" (
    "CategoriesId" integer NOT NULL,
    "ProductsId" integer NOT NULL
);


ALTER TABLE public."CategorieProduct" OWNER TO postgres;

--
-- Name: Categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Categories" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL
);


ALTER TABLE public."Categories" OWNER TO postgres;

--
-- Name: Categories_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Categories" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Categories_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ClientUsers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ClientUsers" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "LastName" text NOT NULL,
    "UserName" text NOT NULL,
    "PhoneNumber" text NOT NULL,
    "UserAccountId" text NOT NULL
);


ALTER TABLE public."ClientUsers" OWNER TO postgres;

--
-- Name: ClientUsers_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ClientUsers" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ClientUsers_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Dates; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Dates" (
    "Id" integer NOT NULL,
    "Time" timestamp with time zone NOT NULL,
    "ServiceId" integer NOT NULL,
    "PetId" integer NOT NULL,
    "StateDate" integer DEFAULT 0 NOT NULL
);


ALTER TABLE public."Dates" OWNER TO postgres;

--
-- Name: Dates_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Dates" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Dates_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: DetailSales; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."DetailSales" (
    "Id" integer NOT NULL,
    "SubTotal" real NOT NULL,
    "Quantity" integer NOT NULL,
    "SaleId" integer NOT NULL,
    "ProductId" integer NOT NULL
);


ALTER TABLE public."DetailSales" OWNER TO postgres;

--
-- Name: DetailSales_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."DetailSales" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."DetailSales_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: MedicalHistories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."MedicalHistories" (
    "Id" integer NOT NULL,
    "Diagnostic" text,
    "Medic" text,
    "Time" timestamp with time zone NOT NULL,
    "PetId" integer NOT NULL
);


ALTER TABLE public."MedicalHistories" OWNER TO postgres;

--
-- Name: MedicalHistories_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."MedicalHistories" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."MedicalHistories_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Pets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Pets" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Type" text NOT NULL,
    "Race" text NOT NULL,
    "Birthday" date NOT NULL,
    "Weight" real NOT NULL,
    "Photo" text,
    "ClientUserId" integer NOT NULL
);


ALTER TABLE public."Pets" OWNER TO postgres;

--
-- Name: Pets_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Pets" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Pets_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Products" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Price" real NOT NULL,
    "Stock" integer NOT NULL,
    "Description" text,
    "Image" text
);


ALTER TABLE public."Products" OWNER TO postgres;

--
-- Name: Products_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Products" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Products_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Sales; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Sales" (
    "Id" integer NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "Total" real NOT NULL,
    "ClientUserId" integer NOT NULL
);


ALTER TABLE public."Sales" OWNER TO postgres;

--
-- Name: Sales_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Sales" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Sales_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Services; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Services" (
    "Id" integer NOT NULL,
    "Type" text NOT NULL,
    "Description" text,
    "Price" real NOT NULL
);


ALTER TABLE public."Services" OWNER TO postgres;

--
-- Name: Services_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Services" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Services_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: Addresses; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Addresses" ("Id", "City", "Province", "Neighborhood", "Street", "Number", "ClientUserId") FROM stdin;
\.


--
-- Data for Name: AspNetRoleClaims; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetRoleClaims" ("Id", "RoleId", "ClaimType", "ClaimValue") FROM stdin;
\.


--
-- Data for Name: AspNetRoles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetRoles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") FROM stdin;
\.


--
-- Data for Name: AspNetUserClaims; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetUserClaims" ("Id", "UserId", "ClaimType", "ClaimValue") FROM stdin;
\.


--
-- Data for Name: AspNetUserLogins; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetUserLogins" ("LoginProvider", "ProviderKey", "ProviderDisplayName", "UserId") FROM stdin;
\.


--
-- Data for Name: AspNetUserRoles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetUserRoles" ("UserId", "RoleId") FROM stdin;
\.


--
-- Data for Name: AspNetUserTokens; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetUserTokens" ("UserId", "LoginProvider", "Name", "Value") FROM stdin;
\.


--
-- Data for Name: AspNetUsers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetUsers" ("Id", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") FROM stdin;
a0559d60-61ea-4330-9b20-8a589410ee5a	antonio@email.com	ANTONIO@EMAIL.COM	antonio@email.com	ANTONIO@EMAIL.COM	f	AQAAAAIAAYagAAAAEMfQaT4XkXR+3xZaQEkn0pjgy3uqvjXn9+O5jqFn+MhqdYYVO+HW95czAMAbSS0VbQ==	STLX4XVLZXKIG3K5QT7DEUGEZTHN3ODV	f5e3f370-b53d-4fb8-972d-f3030dad78aa	\N	f	f	\N	t	0
\.


--
-- Data for Name: CategorieProduct; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."CategorieProduct" ("CategoriesId", "ProductsId") FROM stdin;
\.


--
-- Data for Name: Categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Categories" ("Id", "Name") FROM stdin;
1	Higiene
2	Alimentos
3	Accesorios
4	Entretenimiento
5	Gatos
6	Perros
\.


--
-- Data for Name: ClientUsers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."ClientUsers" ("Id", "Name", "LastName", "UserAccountId") FROM stdin;
\.


--
-- Data for Name: Dates; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Dates" ("Id", "Time", "ServiceId", "PetId", "StateDate") FROM stdin;
\.


--
-- Data for Name: DetailSales; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."DetailSales" ("Id", "SubTotal", "Quantity", "SaleId", "ProductId") FROM stdin;
\.


--
-- Data for Name: MedicalHistories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."MedicalHistories" ("Id", "Diagnostic", "Medic", "Time", "PetId") FROM stdin;
\.


--
-- Data for Name: Pets; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Pets" ("Id", "Name", "Type", "Race", "Birthday", "Weight", "Photo", "ClientUserId") FROM stdin;
\.


--
-- Data for Name: Products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Products" ("Id", "Name", "Price", "Stock", "Description", "Image") FROM stdin;
1	Shampoo para perros	15.99	23	Limpieza e higiene para mascotas	https://acdn.mitiendanube.com/stores/001/145/238/products/osspret-shampoo-tonalizador-blanco-x-250-cc1-4ae072b779337c77d515876089911997-1024-1024.webp
2	Collar para gatos	8.99	15	Accesorio para identificación y seguridad	https://acdn.mitiendanube.com/stores/001/145/238/products/screenshot_51-36d138dcdef37d293e16522805674373-1024-1024.webp
3	Antipulgas y garrapatas	25.99	7	Protección contra parásitos externos	https://acdn.mitiendanube.com/stores/001/145/238/products/20a40-7c408903f56179129e17036219661011-480-0.webp
4	Alimento para perros	39.94	11	Nutrición balanceada para perros adultos	https://acdn.mitiendanube.com/stores/001/145/238/products/urinary-perro-21-3578016b3f083c6ddf16063303514948-1024-1024.webp
\.


--
-- Data for Name: Sales; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Sales" ("Id", "Date", "Total", "ClientUserId") FROM stdin;
\.


--
-- Data for Name: Services; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Services" ("Id", "Type", "Description", "Price") FROM stdin;
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20240220011056_InitialMigration	8.0.0
20240220204846_AddDateState	8.0.0
\.


--
-- Name: Addresses_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Addresses_Id_seq"', 1, false);


--
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AspNetRoleClaims_Id_seq"', 1, false);


--
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AspNetUserClaims_Id_seq"', 1, false);


--
-- Name: Categories_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Categories_Id_seq"', 6, true);


--
-- Name: ClientUsers_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ClientUsers_Id_seq"', 1, false);


--
-- Name: Dates_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Dates_Id_seq"', 1, false);


--
-- Name: DetailSales_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."DetailSales_Id_seq"', 1, false);


--
-- Name: MedicalHistories_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."MedicalHistories_Id_seq"', 1, false);


--
-- Name: Pets_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Pets_Id_seq"', 1, false);


--
-- Name: Products_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Products_Id_seq"', 4, true);


--
-- Name: Sales_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Sales_Id_seq"', 1, false);


--
-- Name: Services_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Services_Id_seq"', 1, false);


--
-- Name: Addresses PK_Addresses; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Addresses"
    ADD CONSTRAINT "PK_Addresses" PRIMARY KEY ("Id");


--
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- Name: CategorieProduct PK_CategorieProduct; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CategorieProduct"
    ADD CONSTRAINT "PK_CategorieProduct" PRIMARY KEY ("CategoriesId", "ProductsId");


--
-- Name: Categories PK_Categories; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Categories"
    ADD CONSTRAINT "PK_Categories" PRIMARY KEY ("Id");


--
-- Name: ClientUsers PK_ClientUsers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ClientUsers"
    ADD CONSTRAINT "PK_ClientUsers" PRIMARY KEY ("Id");


--
-- Name: Dates PK_Dates; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Dates"
    ADD CONSTRAINT "PK_Dates" PRIMARY KEY ("Id");


--
-- Name: DetailSales PK_DetailSales; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."DetailSales"
    ADD CONSTRAINT "PK_DetailSales" PRIMARY KEY ("Id");


--
-- Name: MedicalHistories PK_MedicalHistories; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MedicalHistories"
    ADD CONSTRAINT "PK_MedicalHistories" PRIMARY KEY ("Id");


--
-- Name: Pets PK_Pets; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Pets"
    ADD CONSTRAINT "PK_Pets" PRIMARY KEY ("Id");


--
-- Name: Products PK_Products; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Products"
    ADD CONSTRAINT "PK_Products" PRIMARY KEY ("Id");


--
-- Name: Sales PK_Sales; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sales"
    ADD CONSTRAINT "PK_Sales" PRIMARY KEY ("Id");


--
-- Name: Services PK_Services; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Services"
    ADD CONSTRAINT "PK_Services" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");


--
-- Name: IX_Addresses_ClientUserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Addresses_ClientUserId" ON public."Addresses" USING btree ("ClientUserId");


--
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


--
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


--
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


--
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


--
-- Name: IX_CategorieProduct_ProductsId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_CategorieProduct_ProductsId" ON public."CategorieProduct" USING btree ("ProductsId");


--
-- Name: IX_ClientUsers_UserAccountId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_ClientUsers_UserAccountId" ON public."ClientUsers" USING btree ("UserAccountId");


--
-- Name: IX_Dates_PetId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Dates_PetId" ON public."Dates" USING btree ("PetId");


--
-- Name: IX_Dates_ServiceId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Dates_ServiceId" ON public."Dates" USING btree ("ServiceId");


--
-- Name: IX_DetailSales_ProductId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_DetailSales_ProductId" ON public."DetailSales" USING btree ("ProductId");


--
-- Name: IX_DetailSales_SaleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_DetailSales_SaleId" ON public."DetailSales" USING btree ("SaleId");


--
-- Name: IX_MedicalHistories_PetId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_MedicalHistories_PetId" ON public."MedicalHistories" USING btree ("PetId");


--
-- Name: IX_Pets_ClientUserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Pets_ClientUserId" ON public."Pets" USING btree ("ClientUserId");


--
-- Name: IX_Sales_ClientUserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Sales_ClientUserId" ON public."Sales" USING btree ("ClientUserId");


--
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


--
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");


--
-- Name: Addresses FK_Addresses_ClientUsers_ClientUserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Addresses"
    ADD CONSTRAINT "FK_Addresses_ClientUsers_ClientUserId" FOREIGN KEY ("ClientUserId") REFERENCES public."ClientUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: CategorieProduct FK_CategorieProduct_Categories_CategoriesId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CategorieProduct"
    ADD CONSTRAINT "FK_CategorieProduct_Categories_CategoriesId" FOREIGN KEY ("CategoriesId") REFERENCES public."Categories"("Id") ON DELETE CASCADE;


--
-- Name: CategorieProduct FK_CategorieProduct_Products_ProductsId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CategorieProduct"
    ADD CONSTRAINT "FK_CategorieProduct_Products_ProductsId" FOREIGN KEY ("ProductsId") REFERENCES public."Products"("Id") ON DELETE CASCADE;


--
-- Name: ClientUsers FK_ClientUsers_AspNetUsers_UserAccountId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ClientUsers"
    ADD CONSTRAINT "FK_ClientUsers_AspNetUsers_UserAccountId" FOREIGN KEY ("UserAccountId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: Dates FK_Dates_Pets_PetId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Dates"
    ADD CONSTRAINT "FK_Dates_Pets_PetId" FOREIGN KEY ("PetId") REFERENCES public."Pets"("Id") ON DELETE CASCADE;


--
-- Name: Dates FK_Dates_Services_ServiceId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Dates"
    ADD CONSTRAINT "FK_Dates_Services_ServiceId" FOREIGN KEY ("ServiceId") REFERENCES public."Services"("Id") ON DELETE CASCADE;


--
-- Name: DetailSales FK_DetailSales_Products_ProductId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."DetailSales"
    ADD CONSTRAINT "FK_DetailSales_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES public."Products"("Id") ON DELETE CASCADE;


--
-- Name: DetailSales FK_DetailSales_Sales_SaleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."DetailSales"
    ADD CONSTRAINT "FK_DetailSales_Sales_SaleId" FOREIGN KEY ("SaleId") REFERENCES public."Sales"("Id") ON DELETE CASCADE;


--
-- Name: MedicalHistories FK_MedicalHistories_Pets_PetId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MedicalHistories"
    ADD CONSTRAINT "FK_MedicalHistories_Pets_PetId" FOREIGN KEY ("PetId") REFERENCES public."Pets"("Id") ON DELETE CASCADE;


--
-- Name: Pets FK_Pets_ClientUsers_ClientUserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Pets"
    ADD CONSTRAINT "FK_Pets_ClientUsers_ClientUserId" FOREIGN KEY ("ClientUserId") REFERENCES public."ClientUsers"("Id") ON DELETE CASCADE;


--
-- Name: Sales FK_Sales_ClientUsers_ClientUserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sales"
    ADD CONSTRAINT "FK_Sales_ClientUsers_ClientUserId" FOREIGN KEY ("ClientUserId") REFERENCES public."ClientUsers"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--